-- Scan Invoice
INSERT INTO AP_EVENT_LOG
SELECT 
    CAST(BKPF.BELNR AS VARCHAR(255)) || '-' || CAST(BKPF.BUKRS AS VARCHAR(255)) || '-' || CAST(BKPF.GJAHR AS VARCHAR(255)) AS CASE_ID,
    'Scan Invoice' AS ACTIVITY,
    TO_TIMESTAMP(BKPF.CPUDT || ' ' || LEFT(BKPF.CPUTM, 2) || ':' || SUBSTR(BKPF.CPUTM, 3, 2) || ':' || SUBSTR(BKPF.CPUTM, 5, 2), 'yyyy-MM-dd HH:mm:ss') AS EVENT_TIME,
    BKPF.USNAM AS USER_NAME,
    0.0 AS AMOUNT
FROM BKPF
JOIN BSEG ON BKPF.BELNR = BSEG.BELNR AND BKPF.BUKRS = BSEG.BUKRS AND BKPF.GJAHR = BSEG.GJAHR
WHERE BSEG.KOART = 'K' AND BKPF.STBLG IS NULL 
  AND BKPF.CPUDT IS NOT NULL AND TRIM(BKPF.CPUDT) <> '' 
  AND BKPF.CPUTM IS NOT NULL AND LENGTH(TRIM(BKPF.CPUTM)) = 6;
