-- Create Invoice
INSERT INTO AP_EVENT_LOG
SELECT 
    CAST(BKPF.BELNR AS VARCHAR(255)) || '-' || CAST(BKPF.BUKRS AS VARCHAR(255)) || '-' || CAST(BKPF.GJAHR AS VARCHAR(255)) AS CASE_ID,
    'Create Invoice' AS ACTIVITY,
    TO_TIMESTAMP(BKPF.BUDAT, 'yyyy-MM-dd') AS EVENT_TIME,
    BKPF.USNAM AS USER_NAME,
    SUM(COALESCE(BSEG.DMBTR, 0.0)) AS AMOUNT
FROM BKPF
JOIN BSEG ON BKPF.BELNR = BSEG.BELNR AND BKPF.BUKRS = BSEG.BUKRS AND BKPF.GJAHR = BSEG.GJAHR
WHERE BSEG.KOART = 'K' AND BKPF.STBLG IS NULL AND BKPF.BUDAT IS NOT NULL AND TRIM(BKPF.BUDAT) <> ''
GROUP BY 1, 3, 4;
