-- Set Payment Block
INSERT INTO AP_EVENT_LOG
SELECT 
    CAST(CDHDR.OBJECTID AS VARCHAR(255)) || '-' || CAST(BKPF.BUKRS AS VARCHAR(255)) || '-' || CAST(BKPF.GJAHR AS VARCHAR(255)) AS CASE_ID,
    'Set Payment Block' AS ACTIVITY,
    TO_TIMESTAMP(CDHDR.UDATE, 'yyyy-MM-dd') AS EVENT_TIME,
    CDHDR.USERNAME AS USER_NAME,
    0.0 AS AMOUNT
FROM CDHDR
JOIN CDPOS ON CDHDR.CHANGENR = CDPOS.CHANGENR
JOIN BKPF ON CDHDR.OBJECTID = BKPF.BELNR AND CDHDR.OBJECTCLAS = 'BELEG'
JOIN BSEG ON BKPF.BELNR = BSEG.BELNR AND BKPF.BUKRS = BSEG.BUKRS AND BKPF.GJAHR = BSEG.GJAHR
WHERE CDPOS.FNAME = 'ZLSPR' AND CDPOS.VALUE_NEW <> '' AND BSEG.KOART = 'K' AND CDHDR.UDATE IS NOT NULL AND TRIM(CDHDR.UDATE) <> '';
