-- Clear Invoice
INSERT INTO AP_EVENT_LOG
SELECT 
    CAST(BSEG.BELNR AS VARCHAR(255)) || '-' || CAST(BSEG.BUKRS AS VARCHAR(255)) || '-' || CAST(BSEG.GJAHR AS VARCHAR(255)) AS CASE_ID,
    'Clear Invoice' AS ACTIVITY,
    TO_TIMESTAMP(BSEG.AUGDT, 'yyyy-MM-dd') AS EVENT_TIME,
    NULL AS USER_NAME,
    SUM(COALESCE(BSEG.DMBTR, 0.0)) AS AMOUNT
FROM BSEG
WHERE BSEG.AUGBL IS NOT NULL AND BSEG.AUGDT IS NOT NULL AND TRIM(BSEG.AUGDT) <> '' AND BSEG.KOART = 'K'
GROUP BY 1, 3, 4;
