-- Payment Issued
INSERT INTO AP_EVENT_LOG
SELECT 
    CAST(PAYR.VBLNR AS VARCHAR(255)) || '-' || CAST(PAYR.BUKRS AS VARCHAR(255)) || '-' || CAST(PAYR.GJAHR AS VARCHAR(255)) AS CASE_ID,
    'Payment Issued' AS ACTIVITY,
    TO_TIMESTAMP(PAYR.ZALDT, 'yyyy-MM-dd') AS EVENT_TIME,
    NULL AS USER_NAME,
    SUM(COALESCE(PAYR.RWBTR, 0.0)) AS AMOUNT
FROM PAYR
WHERE PAYR.ZALDT IS NOT NULL AND TRIM(PAYR.ZALDT) <> ''
GROUP BY 1, 3, 4;
