DROP TABLE IF EXISTS AP_CASES;
CREATE TABLE AP_CASES AS
SELECT 
    CAST(BKPF.BELNR AS VARCHAR(255)) || '-' || CAST(BKPF.BUKRS AS VARCHAR(255)) || '-' || CAST(BKPF.GJAHR AS VARCHAR(255)) AS CASE_ID,
    BKPF.BELNR,
    BKPF.BUKRS,
    BKPF.GJAHR,
    MAX(BSEG.LIFNR) AS VENDOR_ID,
    MAX(BKPF.BLDAT) AS DOCUMENT_DATE,
    SUM(COALESCE(BSEG.DMBTR, 0.0)) AS TOTAL_AMOUNT
FROM BKPF
JOIN BSEG ON BKPF.BELNR = BSEG.BELNR AND BKPF.BUKRS = BSEG.BUKRS AND BKPF.GJAHR = BSEG.GJAHR
WHERE BSEG.KOART = 'K' AND BKPF.STBLG IS NULL
GROUP BY 1, 2, 3, 4;
