DROP TABLE IF EXISTS AP_EVENT_LOG;
CREATE TABLE AP_EVENT_LOG (
    CASE_ID VARCHAR(255),
    ACTIVITY VARCHAR(255),
    EVENT_TIME TIMESTAMP,
    USER_NAME VARCHAR(255),
    AMOUNT DECIMAL(15,2)
);

-- Scan Invoice
INSERT INTO AP_EVENT_LOG
SELECT 
    CAST(BKPF.BELNR AS VARCHAR(255)) || '-' || CAST(BKPF.BUKRS AS VARCHAR(255)) || '-' || CAST(BKPF.GJAHR AS VARCHAR(255)) AS CASE_ID,
    'Scan Invoice' AS ACTIVITY,
    TO_TIMESTAMP(BKPF.CPUDT || ' ' || LEFT(BKPF.CPUTM, 2) || ':' || SUBSTR(BKPF.CPUTM, 3, 2) || ':' || SUBSTR(BKPF.CPUTM, 5, 2), 'yyyy-MM-dd HH:mm:ss') AS EVENT_TIME,
    BKPF.USNAM AS USER_NAME,
    0.0 AS AMOUNT
FROM BKPF
JOIN BSEG ON BKPF.BELNR = BSEG.BELNR AND BKPF.BUKRS = BSEG.BUKRS AND BKPF.GJAHR = BSEG.GJAHR
WHERE BSEG.KOART = 'K' AND BKPF.STBLG IS NULL 
  AND BKPF.CPUDT IS NOT NULL AND TRIM(BKPF.CPUDT) <> '' 
  AND BKPF.CPUTM IS NOT NULL AND LENGTH(TRIM(BKPF.CPUTM)) = 6;

-- Create Invoice
INSERT INTO AP_EVENT_LOG
SELECT 
    CAST(BKPF.BELNR AS VARCHAR(255)) || '-' || CAST(BKPF.BUKRS AS VARCHAR(255)) || '-' || CAST(BKPF.GJAHR AS VARCHAR(255)) AS CASE_ID,
    'Create Invoice' AS ACTIVITY,
    TO_TIMESTAMP(BKPF.BUDAT, 'yyyy-MM-dd') AS EVENT_TIME,
    BKPF.USNAM AS USER_NAME,
    SUM(COALESCE(BSEG.DMBTR, 0.0)) AS AMOUNT
FROM BKPF
JOIN BSEG ON BKPF.BELNR = BSEG.BELNR AND BKPF.BUKRS = BSEG.BUKRS AND BKPF.GJAHR = BSEG.GJAHR
WHERE BSEG.KOART = 'K' AND BKPF.STBLG IS NULL AND BKPF.BUDAT IS NOT NULL AND TRIM(BKPF.BUDAT) <> ''
GROUP BY 1, 3, 4;

-- Set Payment Block
INSERT INTO AP_EVENT_LOG
SELECT 
    CAST(CDHDR.OBJECTID AS VARCHAR(255)) || '-' || CAST(BKPF.BUKRS AS VARCHAR(255)) || '-' || CAST(BKPF.GJAHR AS VARCHAR(255)) AS CASE_ID,
    'Set Payment Block' AS ACTIVITY,
    TO_TIMESTAMP(CDHDR.UDATE, 'yyyy-MM-dd') AS EVENT_TIME,
    CDHDR.USERNAME AS USER_NAME,
    0.0 AS AMOUNT
FROM CDHDR
JOIN CDPOS ON CDHDR.CHANGENR = CDPOS.CHANGENR
JOIN BKPF ON CDHDR.OBJECTID = BKPF.BELNR AND CDHDR.OBJECTCLAS = 'BELEG'
JOIN BSEG ON BKPF.BELNR = BSEG.BELNR AND BKPF.BUKRS = BSEG.BUKRS AND BKPF.GJAHR = BSEG.GJAHR
WHERE CDPOS.FNAME = 'ZLSPR' AND CDPOS.VALUE_NEW <> '' AND BSEG.KOART = 'K' AND CDHDR.UDATE IS NOT NULL AND TRIM(CDHDR.UDATE) <> '';

-- Clear Invoice
INSERT INTO AP_EVENT_LOG
SELECT 
    CAST(BSEG.BELNR AS VARCHAR(255)) || '-' || CAST(BSEG.BUKRS AS VARCHAR(255)) || '-' || CAST(BSEG.GJAHR AS VARCHAR(255)) AS CASE_ID,
    'Clear Invoice' AS ACTIVITY,
    TO_TIMESTAMP(BSEG.AUGDT, 'yyyy-MM-dd') AS EVENT_TIME,
    NULL AS USER_NAME,
    SUM(COALESCE(BSEG.DMBTR, 0.0)) AS AMOUNT
FROM BSEG
WHERE BSEG.AUGBL IS NOT NULL AND BSEG.AUGDT IS NOT NULL AND TRIM(BSEG.AUGDT) <> '' AND BSEG.KOART = 'K'
GROUP BY 1, 3, 4;

-- Payment Issued
INSERT INTO AP_EVENT_LOG
SELECT 
    CAST(PAYR.VBLNR AS VARCHAR(255)) || '-' || CAST(PAYR.BUKRS AS VARCHAR(255)) || '-' || CAST(PAYR.GJAHR AS VARCHAR(255)) AS CASE_ID,
    'Payment Issued' AS ACTIVITY,
    TO_TIMESTAMP(PAYR.ZALDT, 'yyyy-MM-dd') AS EVENT_TIME,
    NULL AS USER_NAME,
    SUM(COALESCE(PAYR.RWBTR, 0.0)) AS AMOUNT
FROM PAYR
WHERE PAYR.ZALDT IS NOT NULL AND TRIM(PAYR.ZALDT) <> ''
GROUP BY 1, 3, 4;

DROP TABLE IF EXISTS AP_CASES;
CREATE TABLE AP_CASES AS
SELECT 
    CAST(BKPF.BELNR AS VARCHAR(255)) || '-' || CAST(BKPF.BUKRS AS VARCHAR(255)) || '-' || CAST(BKPF.GJAHR AS VARCHAR(255)) AS CASE_ID,
    BKPF.BELNR,
    BKPF.BUKRS,
    BKPF.GJAHR,
    MAX(BSEG.LIFNR) AS VENDOR_ID,
    MAX(BKPF.BLDAT) AS DOCUMENT_DATE,
    SUM(COALESCE(BSEG.DMBTR, 0.0)) AS TOTAL_AMOUNT
FROM BKPF
JOIN BSEG ON BKPF.BELNR = BSEG.BELNR AND BKPF.BUKRS = BSEG.BUKRS AND BKPF.GJAHR = BSEG.GJAHR
WHERE BSEG.KOART = 'K' AND BKPF.STBLG IS NULL
GROUP BY 1, 2, 3, 4;