DROP TABLE IF EXISTS P2P_EVENT_LOG;
CREATE TABLE P2P_EVENT_LOG (
    CASE_ID VARCHAR(255),
    ACTIVITY VARCHAR(255),
    EVENT_TIME TIMESTAMP,
    USER_NAME VARCHAR(255),
    AMOUNT DECIMAL(15,2)
);
