-- Create Purchase Requisition
INSERT INTO P2P_EVENT_LOG
SELECT EBELN AS CASE_ID, 'Create Purchase Requisition' AS ACTIVITY, TO_TIMESTAMP(BADAT, 'yyyy-MM-dd') AS EVENT_TIME, NULL AS USER_NAME, 0.0 AS AMOUNT
FROM EBAN WHERE EBELN IS NOT NULL AND BADAT IS NOT NULL AND TRIM(BADAT) <> '';
