-- Create Purchase Order Item
INSERT INTO P2P_EVENT_LOG
SELECT EKKO.EBELN AS CASE_ID, 'Create Purchase Order Item' AS ACTIVITY, TO_TIMESTAMP(EKKO.BEDAT, 'yyyy-MM-dd') AS EVENT_TIME, EKKO.ERNAM AS USER_NAME, SUM(COALESCE(EKPO.NETWR, 0.0)) AS AMOUNT
FROM EKKO JOIN EKPO ON EKKO.EBELN = EKPO.EBELN WHERE EKKO.LOEKZ IS NULL AND EKPO.LOEKZ IS NULL AND EKKO.BEDAT IS NOT NULL GROUP BY EKKO.EBELN, EKKO.BEDAT, EKKO.ERNAM;
