-- Record Goods Receipt
INSERT INTO P2P_EVENT_LOG
SELECT MSEG.EBELN AS CASE_ID, 'Record Goods Receipt' AS ACTIVITY, TO_TIMESTAMP(MKPF.BUDAT, 'yyyy-MM-dd') AS EVENT_TIME, MKPF.USNAM AS USER_NAME, SUM(COALESCE(MSEG.MENGE, 0.0)) AS AMOUNT
FROM MSEG JOIN MKPF ON MSEG.MBLNR = MKPF.MBLNR AND MSEG.MJAHR = MKPF.MJAHR WHERE MSEG.BWART = '101' AND MSEG.SHKZG <> 'H' AND MSEG.EBELN IS NOT NULL GROUP BY MSEG.EBELN, MKPF.BUDAT, MKPF.USNAM;
