-- First Invoice Created
INSERT INTO P2P_EVENT_LOG
SELECT EBELN AS CASE_ID, 'First Invoice Created' AS ACTIVITY, MIN(TO_TIMESTAMP(BUDAT, 'yyyy-MM-dd')) AS EVENT_TIME, NULL AS USER_NAME, SUM(COALESCE(WRBTR, 0.0)) AS AMOUNT
FROM EKBE WHERE VGABE = '2' AND EBELN IS NOT NULL AND BUDAT IS NOT NULL GROUP BY EBELN;
