-- Clear Invoice
INSERT INTO P2P_EVENT_LOG
SELECT EBELN AS CASE_ID, 'Clear Invoice' AS ACTIVITY, TO_TIMESTAMP(AUGDT, 'yyyy-MM-dd') AS EVENT_TIME, NULL AS USER_NAME, SUM(COALESCE(DMBTR, 0.0)) AS AMOUNT
FROM BSEG WHERE AUGBL IS NOT NULL AND AUGDT IS NOT NULL AND EBELN IS NOT NULL AND EBELN <> '' GROUP BY EBELN, AUGDT;
