-- Change Purchase Requisition
INSERT INTO P2P_EVENT_LOG
SELECT OBJECTID AS CASE_ID, 'Change Purchase Requisition' AS ACTIVITY, TO_TIMESTAMP(UDATE, 'yyyy-MM-dd') AS EVENT_TIME, USERNAME AS USER_NAME, 0.0 AS AMOUNT
FROM CDHDR WHERE OBJECTCLAS = 'BANF' AND UDATE IS NOT NULL;
