DROP TABLE IF EXISTS P2P_CASES;
CREATE TABLE P2P_CASES AS
SELECT EBELN AS CASE_ID, EBELN, MAX(BUKRS) AS BUKRS, MAX(LIFNR) AS LIFNR, MIN(BEDAT) AS PO_DATE, MAX(BSART) AS BSART, MAX(EKORG) AS EKORG
FROM EKKO WHERE LOEKZ IS NULL GROUP BY EBELN;
