-- Payment Block
INSERT INTO P2P_EVENT_LOG
SELECT CDHDR.OBJECTID AS CASE_ID, 'Payment Block' AS ACTIVITY, TO_TIMESTAMP(CDHDR.UDATE, 'yyyy-MM-dd') AS EVENT_TIME, CDHDR.USERNAME AS USER_NAME, 0.0 AS AMOUNT
FROM CDHDR JOIN CDPOS ON CDHDR.CHANGENR = CDPOS.CHANGENR WHERE CDPOS.FNAME = 'ZLSPR' AND CDPOS.VALUE_NEW <> '';
