DROP TABLE IF EXISTS P2P_EVENT_LOG;
CREATE TABLE P2P_EVENT_LOG (
    CASE_ID VARCHAR(255),
    ACTIVITY VARCHAR(255),
    EVENT_TIME TIMESTAMP,
    USER_NAME VARCHAR(255),
    AMOUNT DECIMAL(15,2)
);

-- Create Purchase Requisition
INSERT INTO P2P_EVENT_LOG
SELECT EBELN AS CASE_ID, 'Create Purchase Requisition' AS ACTIVITY, TO_TIMESTAMP(BADAT, 'yyyy-MM-dd') AS EVENT_TIME, NULL AS USER_NAME, 0.0 AS AMOUNT
FROM EBAN WHERE EBELN IS NOT NULL AND BADAT IS NOT NULL AND TRIM(BADAT) <> '';

-- Create Purchase Order Item
INSERT INTO P2P_EVENT_LOG
SELECT EKKO.EBELN AS CASE_ID, 'Create Purchase Order Item' AS ACTIVITY, TO_TIMESTAMP(EKKO.BEDAT, 'yyyy-MM-dd') AS EVENT_TIME, EKKO.ERNAM AS USER_NAME, SUM(COALESCE(EKPO.NETWR, 0.0)) AS AMOUNT
FROM EKKO JOIN EKPO ON EKKO.EBELN = EKPO.EBELN WHERE EKKO.LOEKZ IS NULL AND EKPO.LOEKZ IS NULL AND EKKO.BEDAT IS NOT NULL GROUP BY EKKO.EBELN, EKKO.BEDAT, EKKO.ERNAM;

-- Record Goods Receipt
INSERT INTO P2P_EVENT_LOG
SELECT MSEG.EBELN AS CASE_ID, 'Record Goods Receipt' AS ACTIVITY, TO_TIMESTAMP(MKPF.BUDAT, 'yyyy-MM-dd') AS EVENT_TIME, MKPF.USNAM AS USER_NAME, SUM(COALESCE(MSEG.MENGE, 0.0)) AS AMOUNT
FROM MSEG JOIN MKPF ON MSEG.MBLNR = MKPF.MBLNR AND MSEG.MJAHR = MKPF.MJAHR WHERE MSEG.BWART = '101' AND MSEG.SHKZG <> 'H' AND MSEG.EBELN IS NOT NULL GROUP BY MSEG.EBELN, MKPF.BUDAT, MKPF.USNAM;

-- First Invoice Created
INSERT INTO P2P_EVENT_LOG
SELECT EBELN AS CASE_ID, 'First Invoice Created' AS ACTIVITY, MIN(TO_TIMESTAMP(BUDAT, 'yyyy-MM-dd')) AS EVENT_TIME, NULL AS USER_NAME, SUM(COALESCE(WRBTR, 0.0)) AS AMOUNT
FROM EKBE WHERE VGABE = '2' AND EBELN IS NOT NULL AND BUDAT IS NOT NULL GROUP BY EBELN;

-- Clear Invoice
INSERT INTO P2P_EVENT_LOG
SELECT EBELN AS CASE_ID, 'Clear Invoice' AS ACTIVITY, TO_TIMESTAMP(AUGDT, 'yyyy-MM-dd') AS EVENT_TIME, NULL AS USER_NAME, SUM(COALESCE(DMBTR, 0.0)) AS AMOUNT
FROM BSEG WHERE AUGBL IS NOT NULL AND AUGDT IS NOT NULL AND EBELN IS NOT NULL AND EBELN <> '' GROUP BY EBELN, AUGDT;

-- Change Purchase Order (Generic)
INSERT INTO P2P_EVENT_LOG
SELECT OBJECTID AS CASE_ID, 'Change Purchase Order' AS ACTIVITY, TO_TIMESTAMP(UDATE, 'yyyy-MM-dd') AS EVENT_TIME, USERNAME AS USER_NAME, 0.0 AS AMOUNT
FROM CDHDR WHERE OBJECTCLAS = 'EINKBELEG' AND UDATE IS NOT NULL;

-- Change Purchase Requisition
INSERT INTO P2P_EVENT_LOG
SELECT OBJECTID AS CASE_ID, 'Change Purchase Requisition' AS ACTIVITY, TO_TIMESTAMP(UDATE, 'yyyy-MM-dd') AS EVENT_TIME, USERNAME AS USER_NAME, 0.0 AS AMOUNT
FROM CDHDR WHERE OBJECTCLAS = 'BANF' AND UDATE IS NOT NULL;

-- Payment Block
INSERT INTO P2P_EVENT_LOG
SELECT CDHDR.OBJECTID AS CASE_ID, 'Payment Block' AS ACTIVITY, TO_TIMESTAMP(CDHDR.UDATE, 'yyyy-MM-dd') AS EVENT_TIME, CDHDR.USERNAME AS USER_NAME, 0.0 AS AMOUNT
FROM CDHDR JOIN CDPOS ON CDHDR.CHANGENR = CDPOS.CHANGENR WHERE CDPOS.FNAME = 'ZLSPR' AND CDPOS.VALUE_NEW <> '';

DROP TABLE IF EXISTS P2P_CASES;
CREATE TABLE P2P_CASES AS
SELECT EBELN AS CASE_ID, EBELN, MAX(BUKRS) AS BUKRS, MAX(LIFNR) AS LIFNR, MIN(BEDAT) AS PO_DATE, MAX(BSART) AS BSART, MAX(EKORG) AS EKORG
FROM EKKO WHERE LOEKZ IS NULL GROUP BY EBELN;